version: "3"

services:
  nodVACd:
    image: VACio/VAC:latest
    command: /opt/VACio/bin/nodVACd.sh --data-dir /opt/VACio/bin/data-dir -e --http-alias=nodVACd:8888 --http-alias=127.0.0.1:8888 --http-alias=localhost:8888
    hostname: nodVACd
    ports:
      - 8888:8888
      - 9876:9876
    expose:
      - "8888"
    volumes:
      - nodVAC-data-volume:/opt/VACio/bin/data-dir
    cap_add:
      - IPC_LOCK
    stop_grace_period: 10m

  kVACd:
    image: VACio/VAC:latest
    command: /opt/VACio/bin/kVACd --wallet-dir /opt/VACio/bin/data-dir --http-server-address=127.0.0.1:8900 --http-alias=kVACd:8900 --http-alias=localhost:8900
    hostname: kVACd
    links:
      - nodVACd
    volumes:
      - kVACd-data-volume:/opt/VACio/bin/data-dir
    stop_grace_period: 10m

volumes:
 nodVAC-data-volume:
   external: true
 kVACd-data-volume:
   external: true
